/**
 * Mongoose model for dashboard/analyst sessions.
 *
 * A "session" is a live WebSocket client connected to the alert stream
 * (typically a browser tab showing the SentinelX dashboard). Used for
 * the stats endpoint ("N analysts watching") and for auditing who was
 * looking when an incident hit.
 */
'use strict';

const mongoose = require('mongoose');

const { Schema } = mongoose;

const sessionSchema = new Schema(
  {
    /** WebSocket connection id (generated by the backend) */
    id: { type: String, required: true, unique: true },

    /** Client IP (best effort, proxy headers not trusted) */
    ip: { type: String, default: '' },

    /** User-Agent of the connecting client */
    user_agent: { type: String, default: '' },

    connected_at: { type: Date, default: Date.now },
    last_seen_at: { type: Date, default: Date.now },

    /** false once the WebSocket closes */
    active: { type: Boolean, default: true, index: true },
  },
  { timestamps: false }
);

// Expire closed sessions after 24h; active ones are pruned by last_seen.
sessionSchema.index({ last_seen_at: 1 }, { expireAfterSeconds: 24 * 3600 });

module.exports = mongoose.model('Session', sessionSchema);
