#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# SentinelX — automated host deployment (Debian / Ubuntu / Kali)
#
#   sudo bash deployment/install.sh
#
# What it does:
#   1. installs build + runtime dependencies (libpcap, YARA, Node.js, nginx)
#   2. copies the repository to /opt/sentinelx
#   3. builds the C++ engine
#   4. installs backend npm dependencies and generates /opt/sentinelx/.env
#   5. builds the React dashboard
#   6. installs systemd units (engine + backend), enables them
#   7. installs the nginx reverse-proxy site (dashboard on :80)
#
# Environment overrides:
#   SENTINELX_INTERFACE   capture interface (default: auto-detect, else eth0)
#   SENTINELX_MMDB        path to a GeoLite2-City.mmdb to enable geo-IP
#   SENTINELX_MONGO_URI   MongoDB URI (default: local 27017)
#
# Requires: root. Idempotent — safe to re-run.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

INSTALL_DIR="/opt/sentinelx"
SOCKET_DIR="/run/sentinelx"
SOCKET_PATH="${SOCKET_DIR}/alerts.sock"
PID_FILE="${SOCKET_DIR}/sentinelx.pid"
BACKEND_PORT=4000
MONGO_URI="${SENTINELX_MONGO_URI:-mongodb://127.0.0.1:27017/sentinelx}"
MMDB="${SENTINELX_MMDB:-}"

log()  { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[install]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[install]\033[0m %s\n' "$*" >&2; exit 1; }

# ── 0. sanity ─────────────────────────────────────────────────────────────────
[ "$(id -u)" = "0" ] || die "run as root (sudo bash deployment/install.sh)"
[ -f "$(dirname "$0")/../engine/CMakeLists.txt" ] || die "run from a checkout of SentinelX (deployment/install.sh must sit next to engine/)"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── 1. dependencies ───────────────────────────────────────────────────────────
log "Installing system packages…"
apt-get update -qq
apt-get install -y -qq \
    build-essential cmake git pkg-config rsync \
    libpcap-dev libyara-dev \
    nginx curl ca-certificates xz-utils

if ! command -v node >/dev/null 2>&1 || [ "$(node -p 'process.versions.node.split(".")[0]')" -lt 18 ]; then
    log "Installing Node.js 20 (NodeSource)…"
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y -qq nodejs
fi
log "node $(node --version), npm $(npm --version), g++ $(g++ --version | head -1 | awk '{print $3}')"

# ── 2. copy sources ───────────────────────────────────────────────────────────
log "Copying repository to ${INSTALL_DIR}…"
mkdir -p "$INSTALL_DIR"
if [ "$REPO_ROOT" != "$INSTALL_DIR" ]; then
    rsync -a --delete \
        --exclude '.git' \
        --exclude 'engine/build' \
        --exclude '*/node_modules' \
        --exclude 'dashboard/dist' \
        "$REPO_ROOT/" "$INSTALL_DIR/"
fi

# ── 3. build the engine ───────────────────────────────────────────────────────
log "Building the C++ engine…"
cmake -S "$INSTALL_DIR/engine" -B "$INSTALL_DIR/engine/build" -DCMAKE_BUILD_TYPE=Release
cmake --build "$INSTALL_DIR/engine/build" -j"$(nproc)"
"$INSTALL_DIR/engine/build/sentinelx" --help >/dev/null 2>&1 || true

# ── 4. backend ────────────────────────────────────────────────────────────────
log "Installing backend dependencies…"
cd "$INSTALL_DIR/backend"
npm ci --no-audit --no-fund 2>/dev/null || npm install --no-audit --no-fund

# Auto-detect a non-loopback interface if not overridden.
IFACE="${SENTINELX_INTERFACE:-}"
if [ -z "$IFACE" ] && command -v ip >/dev/null; then
    IFACE="$(ip -o -4 route show default 2>/dev/null | awk '{print $5; exit}')"
fi
IFACE="${IFACE:-eth0}"

cat > "$INSTALL_DIR/backend/.env" <<EOF
# generated by deployment/install.sh on $(date -Is)
PORT=${BACKEND_PORT}
MONGO_URI=${MONGO_URI}
ENGINE_SOCKET=${SOCKET_PATH}
ENGINE_PID_FILE=${PID_FILE}
RULES_DIR=${INSTALL_DIR}/engine/rules
CORS_ORIGIN=*
EOF
if [ -n "$MMDB" ]; then
    echo "GEOIP_MMDB=${MMDB}" >> "$INSTALL_DIR/backend/.env"
    [ -f "$MMDB" ] || warn "GEOIP_MMDB=${MMDB} is not readable yet — geo-IP stays disabled until it is"
fi
log "Backend .env written (interface hint: ${IFACE})"

# ── 5. dashboard ──────────────────────────────────────────────────────────────
log "Building the dashboard…"
cd "$INSTALL_DIR/dashboard"
npm ci --no-audit --no-fund 2>/dev/null || npm install --no-audit --no-fund
npm run build

# ── 6. runtime dir + systemd units ────────────────────────────────────────────
log "Installing systemd units…"
mkdir -p "$SOCKET_DIR"
chown root:root "$SOCKET_DIR"

# Engine wrapper: writes the pidfile the backend's rules hot-reload endpoint
# reads, then exec's the engine (same PID survives the exec).
cat > /usr/local/sbin/sentinelx-engine-run <<EOF
#!/bin/sh
mkdir -p ${SOCKET_DIR}
echo \$\$ > ${PID_FILE}
exec ${INSTALL_DIR}/engine/build/sentinelx \\
    -i ${IFACE} \\
    --socket ${SOCKET_PATH} \\
    --rules ${INSTALL_DIR}/engine/rules \\
    --output socket
EOF
chmod 755 /usr/local/sbin/sentinelx-engine-run

sed -e "s|__INSTALL_DIR__|${INSTALL_DIR}|g" \
    "$INSTALL_DIR/deployment/sentinelx.service" > /etc/systemd/system/sentinelx.service
sed -e "s|__INSTALL_DIR__|${INSTALL_DIR}|g" -e "s|__PORT__|${BACKEND_PORT}|g" \
    "$INSTALL_DIR/deployment/sentinelx-backend.service" > /etc/systemd/system/sentinelx-backend.service

systemctl daemon-reload
systemctl enable sentinelx-backend.service
systemctl enable sentinelx.service
log "Enabled: sentinelx (engine), sentinelx-backend (API + WS)"

# ── 7. nginx ──────────────────────────────────────────────────────────────────
log "Configuring nginx (dashboard on :80)…"
cp "$INSTALL_DIR/deployment/nginx.conf" /etc/nginx/sites-available/sentinelx
ln -sf /etc/nginx/sites-available/sentinelx /etc/nginx/sites-enabled/sentinelx
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable nginx
systemctl reload nginx 2>/dev/null || systemctl start nginx

# ── done ──────────────────────────────────────────────────────────────────────
log "Deployment complete."
cat <<EOF

  Next steps
  ─────────────────────────────────────────────────
  1. Start MongoDB if you want persistent storage:
       systemctl start mongod        # or set MONGO_URI to a remote cluster
  2. Start the stack:
       systemctl start sentinelx-backend
       systemctl start sentinelx
  3. Open the dashboard:
       http://localhost/             (nginx :80 → dashboard + API proxy)

  Logs:  journalctl -u sentinelx -f        journalctl -u sentinelx-backend -f
  Rules: manage from the dashboard (Settings → YARA rules) or
         POST /api/rules/reload to hot-reload the running engine.

  ${IFACE} is the capture interface (re-run with SENTINELX_INTERFACE=<if> to change).
EOF
